name = "temp-email-worker"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "temp-email-db"
database_id = "3015c5da-c6be-4832-9b98-43103e1ae0e4"

[triggers]
crons = ["0 * * * *"] # 每小时执行一次，检查并清理超过48小时的数据
